# THIS IS NOT A PRODUCTION ENVIRONMENT
version: '3.9'

services:
  db:
    image: mariadb
    container_name: database
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./maria_store:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=demo
      - MYSQL_USER=demo
      - MYSQL_DATABASE=sim
      - MYSQL_HOST=localhost
      - MYSQL_POR=3306
