# Generated by Django 4.0.5 on 2022-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20220619_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenario',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
