# Generated by Django 4.0.5 on 2022-06-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userscenario_ended'),
        ('app', '0006_scenariostate_budget_scenariostate_total_tasks'),
    ]

    operations = [
    ]
