# Generated by Django 4.0.5 on 2022-06-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_explanation'),
        ('app', '0008_remove_event_effect_type_remove_event_effect_value_and_more'),
    ]

    operations = [
    ]
