# Generated by Django 4.0.5 on 2022-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20220628_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='familiar_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
