# Generated by Django 4.0.5 on 2022-07-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20220628_1821'),
        ('app', '0010_alter_member_familiar_tasks'),
    ]

    operations = [
    ]
