# Generated by Django 4.0.5 on 2022-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20220702_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostate',
            name='poison_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenariostate',
            name='poisson_sum',
            field=models.IntegerField(default=0),
        ),
    ]
