# Generated by Django 4.0.5 on 2022-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_scenariostate_poison_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioconfig',
            name='randomness',
            field=models.TextField(default='full'),
        ),
    ]
